### ISSUE TITLE
java not found

### ISSUE THREAD

**Issue by mac-linux-free** [gozoinks/unifi-pfsense#116] opened 2018-08-19 20:35 UTC
hello.. on a new pfsense install the script is not working...start unifi java not found...I enabled freebsd repo and installed openjdk8 and after that the script is working.

**Comment by mac-linux-free** [comment] 2018-08-21 11:29
the problem is getting worse...I could not connect to the unifi wizard..it is a fresh installed pfsense with the workaround above

**Comment by pfSenseNut** [comment] 2018-08-21 13:58
Well, I got it working on one pfSense box but when I went back to do another one with the instructions I used the first time, I can't get it to work either.  I tried all sorts of things and nothing worked.  Looks like Unifi is going to have to live on a Windows or Linux VM.  Bummer.

**Comment by pfSenseNut** [comment] 2018-08-21 14:17
Alright, I "think" I know where the problem is and if I get time I will try to fix it.  The code is calling for the latest versions of software for Unifi to work, like Java among others.  I did a little digging on the freebsd.org site and noticed that right around the time this unifi-pfsense code stopped working with pfSense was around the time they updated freebsd packages...(early August 2018).  So if we can point the dependent packages to an older freebsd repository I bet it will work again.

**Comment by toredash** [comment] 2018-08-22 20:15
Please check PR https://github.com/gozoinks/unifi-pfsense/pull/117

**Comment by toredash** [comment] 2018-08-25 06:43
PR #117 fixes this. Please close this issue

**Comment by pfSenseNut** [comment] 2018-08-27 19:14
Thanks so much jmbwell for getting this resolved.  Appreciate your work and dedication on this.  Yeah, day jobs aren't much fun ;)

**Closed as completed** 2018-08-27 19:22 UTC
