### ISSUE TITLE
Guest portal broken after upgarding to pfSense2.4

### ISSUE THREAD

**Issue by dvdp** [gozoinks/unifi-pfsense#87] opened 2017-10-15 21:05 UTC
Hi,
I upgraded my pfSense box to 2.4 - that went well. After that, restored my UniFi software, that went fairly smooth too. I jut noticed one problem: the guest portal is not working anymore. I did some research and found this is very likely related to a bug in zlib: 
https://community.ubnt.com/t5/UniFi-Wireless/ERR-CONTENT-DECODING-FAILED-on-guest-portal-customisation/td-p/1903419
I'm now trying to figure out how to get this fixed - if anyone could provide some guidance I would be very grateful ...
Danny

**Comment by lynndixon** [comment] 2017-10-18 05:13
I'm being hit with this as well.  Looking for a solution now, but haven't discovered anything yet.

**Comment by dvdp** [comment] 2017-10-18 06:41
No progress so far - I switched to plan B = use the pfSense captive portal. Our APs are on a separate VLAN that connects to a separate NIC on the pfSense box. Enabling & configuring the pfSense captive portal and disabling the UniFi portal got us going again. I made a dedicated user ('Guest') on the pfSense box and put it in a new group ('guests' again) with only captive portal login rights and the same password as the guest login on the UniFi poretal. Finally hand crafted a portal login page (took some time to make it look somewhat decent - that's what I like about the UniFi portal) - back in business now.
Still working on a few tweaks on the portal page design but that's just polish - it's working.

**Comment by anon12345** [comment] 2017-10-18 14:49
I can't even get my web interface to come up since the 2.4 upgrade, even with a clean install. (removing the /usr/etc/local/UniFi/ folder). It will start from the command line normally, but no webpage comes up on the configured port and I get a string of errors when I shut the service back down.

**Comment by dvdp** [comment] 2017-10-18 14:54
That happended to me too - if I remember well I got things going again using the clean install.
One thing though: look in /usr/local/UniFi/bin and check where the symbolic link mongod points to. I think it was pointing wrongly to /usr/bin/mongod instead of /usr/local/bin/mongod. I replaced it by the correct symbolic link which fixed things (alternatively: if the link is not there create it)

**Comment by anon12345** [comment] 2017-10-18 15:18
Thanks for the help!

I saw what you were refferring to with the symlink:

finishing deferred symbolic links:
  /usr/local/UniFi/bin/mongod -> /usr/bin/mongod
 done.

And updated my symlink:

lrwxr-xr-x   1 root  wheel   21 Oct 16 05:30 mongod -> /usr/local/bin/mongod

But I'm still getting this giant error when running (service unifi.sh stop):

/usr/local/bin: service unifi.sh stop
Signaling the UniFi controller to stop... acknowledged.
Waiting for the UniFi controller to stop (this can take a long time).....org.tuckey.web.filters.urlrewrite.UrlRewriteFilter INFO: destroy called
Exception in thread "launcher" org.springframework.beans.factory.BeanCreationException: Error creating bean with name '?00000' defined in class com.ubnt.service.AppContext: Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [com.ubnt.service.oO0O.D com.ubnt.service.AppContext.?00000()] threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dbService' defined in class com.ubnt.service.AppContext: Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:597)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1055)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:951)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:487)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:296)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:293)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:628)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
        at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:73)
        at com.ubnt.service.B.?O0000(Unknown Source)
        at com.ubnt.service.B.?00000(Unknown Source)
        at com.ubnt.ace.Launcher.main(Unknown Source)
Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [com.ubnt.service.oO0O.D com.ubnt.service.AppContext.?00000()] threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dbService' defined in class com.ubnt.service.AppContext: Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:181)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:586)
        ... 15 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dbService' defined in class com.ubnt.service.AppContext: Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1512)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:521)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:296)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:293)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:305)
        at com.ubnt.service.AppContext$$EnhancerBySpringCGLIB$$9c6af6d.dbService(<generated>)
        at com.ubnt.service.AppContext.?00000(Unknown Source)
        at com.ubnt.service.AppContext$$EnhancerBySpringCGLIB$$9c6af6d.CGLIB$?00000$1(<generated>)
        at com.ubnt.service.AppContext$$EnhancerBySpringCGLIB$$9c6af6d$$FastClassBySpringCGLIB$$7089df3b.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:293)
        at com.ubnt.service.AppContext$$EnhancerBySpringCGLIB$$9c6af6d.?00000(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:160)
        ... 16 more
Caused by: java.lang.NullPointerException
        at com.ubnt.service.new.Q.intsuper(Unknown Source)
        at com.ubnt.service.new.Q.afterPropertiesSet(Unknown Source)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1571)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1509)
        ... 35 more
pgrep: Cannot get process list (kvm_getprocs: No such process)
 stopped.

Hopefully there is a clue in there, but it's over my head.

**Comment by dvdp** [comment] 2017-10-18 15:32
It says 
Error creating bean with name 'dbService'

Really looks like a problem with mongodb to me.
Is mongo actually installed?

**Comment by anon12345** [comment] 2017-10-18 15:48
It looks like it was installed, but I thought I'd reinstall:

/usr/local/bin: pkg delete mongodb
Checking integrity... done (0 conflicting)
Deinstallation has been requested for the following 1 packages (of 0 packages in the universe):

Installed packages to be REMOVED:
        mongodb-2.6.12_2

Number of packages to be removed: 1

The operation will free 182 MiB.

Proceed with deinstalling packages? [y/N]: y
[1/1] Deinstalling mongodb-2.6.12_2...
[1/1] Deleting files for mongodb-2.6.12_2: 100%
==> You should manually remove the "mongodb" user.
==> You should manually remove the "mongodb" group

But getting the following on attempt to resintall:

/usr/local/bin: pkg install mongodb
Updating pfSense-core repository catalogue...
pfSense-core repository is up to date.
Updating pfSense repository catalogue...
pfSense repository is up to date.
All repositories are up to date.
pkg: No packages available to install matching 'mongodb' have been found in the repositories

**Comment by anon12345** [comment] 2017-10-18 23:25
Got mine running, though unfortunately different issue the OP.

I had to start with a: (due to failure of AP's to associate after finally getting GUI up)

pkg delete snappyjava

I had to edit the 'install-unifi.sh' file from:

AddPkg snappy
AddPkg python2
AddPkg v8
AddPkg mongodb
AddPkg unzip
AddPkg pcre

to:

AddPkg snappy
AddPkg python2
AddPkg v8
**AddPkg cyrus-sasl**
AddPkg mongodb**32**
AddPkg unzip
AddPkg pcre

(using https://pkg.freebsd.org/FreeBSD:11:amd64/latest/All/ as a package source refference)

Then it worked!

**Comment by lynndixon** [comment] 2017-10-18 23:32
Try to use the unifi captive portal or even goto the hotspot manager in
unifi, you will likely see the issue we are seeing.

**Comment by alexwasserman** [comment] 2017-10-19 02:13
Getting the same mongo error in server.log.

Running it directly says it's missing a library:

[2.4.0-RELEASE][admin@pfSense.lan]/usr/local/UniFi: bin/mongod
Shared object "libkvm.so.6" not found, required by "mongod"

That library is on the obsoleted files list: https://github.com/pfsense/pfsense/blob/master/src/etc/pfSense.obsoletedfiles

So, not sure if that's just been removed now.

I see we have 7:
[2.4.0-RELEASE][admin@pfSense.lan]/usr/local/UniFi: ls -lrt /lib/*kvm*
-r--r--r--  1 root  wheel  58944 Oct 10 07:47 /lib/libkvm.so.7

But, linking .6 to .7 just throws up:
Shared object "libssl.so.7" not found, required by "mongod"

**Comment by alexwasserman** [comment] 2017-10-19 02:29
ok - had to fix:
libssl (in /usr/lib)
libcrypto (in /lib)
libkvm (in /lib)

Just created links from the newer to the older versions (hacky but seems to work):

ln -s /usr/lib/libssl.so.8 /usr/lib/libssl.so.7
ln -s /lib/libcrypto.so.8 /lib/libcrypto.so.7
ln -s /lib/libkvm.so.7 /lib/libkvm.so.6

I'd also added the following packages to the script -
AddPkg libressl
AddPkg openssl
AddPkg cyrus-sasl

Not clear which of those are really required.

**Comment by gnkidwell** [comment] 2021-03-13 12:45
Latest script does not have this issue. Closing this.

**Closed by gnkidwell** 2021-03-13 12:45 UTC
