### ISSUE TITLE
Uninstallation Instructions Needed

### ISSUE THREAD

**Issue by andrewpurkett** [gozoinks/unifi-pfsense#148] opened 2019-06-06 05:44 UTC
There’s no instructions on how to properly uninstall the package and it’s dependencies. Can someone please advise what steps to take?

**Comment by alexricher** [comment] 2019-06-16 15:34
I would also be curious as I'm having issue starting the controller lately and I would like to re-install it, if possible. Thanks! :)

**Comment by icem4n** [comment] 2019-08-07 20:24
Would love instructions, but you can re-install by:

1. download a backup from the controller or copy a backup from /usr/local/UniFi/data/backup/*.unf
2. rename /usr/local/UniFi to /usr/local/UniFi.old
3. Run install-unifi.sh

I cannot get an upgrade to work anymore, I am having to load from backup each time after doing the above.

**Comment by jacobq11** [comment] 2020-01-08 19:42
Another vote for Uninstallation Instructions please! 

I migrated my unifi controller to a new VM, and no longer need it on my pfsense.

**Comment by jmbwell** [comment] 2020-08-06 16:42
To uninstall UniFi controller:
```
rm -rf /usr/local/UniFi
rm /usr/local/etc/rc.d/unifi.sh
```

To remove all the dependent packages is a different matter, but I will say that upgrading pfSense tends to clobber all our work, so any unnecessary packages will likely disappear at the next upgrade.

But this is a good point, I should add it to the readme. Thank you.

**Comment by jmbwell** [comment] 2020-08-06 16:51
Duplicate of #109

**Closed by jmbwell** 2020-08-06 16:51 UTC

**Comment by tong2x** [comment] 2020-08-11 05:03
hi please add to documentation
